#cloud-config

## Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: hc2-0
manage_etc_hosts: true

## Set the locale of the system
locale: 'en_GB.UTF-8'

## Set the timezone
## Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: 'Europe/London'

package_reboot_if_required: true
package_update: true
package_upgrade: true

users:
  - name: alan
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh_import_id: None
    lock_passwd: true
    ssh_pwauth: false
    ssh_authorized_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINqNVcWqkNPa04xMXls78lODJ21W43ZX6NlOtFENYUGF'

growpart:
  mode: auto
  devices: ['/']

write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            addresses:
              - 192.168.86.60/24
            gateway4: 192.168.86.1
            nameservers:
              addresses:
                - 192.168.86.1

runcmd:
  - [sudo, netplan, --debug, apply]